 /*======================================
 *
 * Author: Hossam Nasr
 *
 * Module: Ultrasonic
 *
 * File Name: ultrasonic.h
 *
 *=======================================*/


#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

/* Ultrasonic HW Ports and Pins IDs */
#define ULTRASONIC_SENSOR_TRIGGER_PORT_ID	PORTB_ID
#define ULTRASONIC_SENSOR_TRIGGER_PIN_ID    PIN5_ID

/* Specify with factor which the time should be divided by to get the distance */
#define DIVISION_FACTOR	58

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * Initialize the Ultrasonic:
 * 1. Initialize the ICU driver as required.
 * 2. Setup the ICU call back function.
 * 3. Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void);


/*
 * Description: Function to Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);


/*
 * Description :
 * Get the distance from the sensor:
 * 1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2. Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);


/*
 * Description :
 * 1. This is the call back function called by the ICU driver.
 * 2. This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
